DEAD_ServerTitle = "Real Life RPG";
DEAD_ServerShort = "RLRPG";
DEAD_ScriptEnable = true; // Boolean to judge whether these scripts are to be used;
publicvariable "DEAD_ScriptEnable"; // Just in case someone does something nasty like disabling it on the fly.
Donate_id = [];
Donate_id2 = [];
Donate_id3= [];
Donate_id4 = [];
Donate_id5 = [];
Donate_id6 = [];
TopDonator_id = [];
BankIncrease1_id = [];
BankIncrease2_id = [];
BankIncrease3_id = [];
WeightIncrease1_id = [];
WeightIncrease2_id = [];
WeightIncrease3_id = [];
CarSaveIncrease1_id = [];
CarSaveIncrease2_id = [];
CarSaveIncrease3_id = [];
PO1_id = [];
PO2_id = [];
PO3_id = [];
Cpl_id = [];
Sgt_id = [];
Lt_id = [];
Cpt_id = [];
Chief_id = [];
Deputy_id = [];
Sheriff_id = [];
K9_id = [];
PDAviation_id = [];
SWAT_id = [];
CoastGuard_id = [];
Undercover_id = [];
EMT1_id = [];
EMT2_id = [];
EMT3_id = [];
FD_id = [];
AirESU_id = [];
ESUCommand_id = [];
TierX_id = [];
adminlevel4  = [];
adminlevel3 = [];
adminlevel2 = [];
SwagDevs = [];
Developer_id = [];


if(!DEAD_ScriptEnable) exitWith{};
// Begin Compiling Functions;
[] execVM "deaddem\errorhint.sqf";
[] execVM "deaddem\successhint.sqf";
[] execVM "deaddem\noticehint.sqf";
[] execVM "deaddem\reportlog.sqf";
[] execVM "deaddem\dispatchHint.sqf";
[] execVM "deaddem\governerhint.sqf";
[] execVM "deaddem\functions.sqf";
[] execVM "deaddem\stat\fn_LoadWhitelist.sqf";

[] call fn_LoadStats;